import { cva, type VariantProps } from 'class-variance-authority';

export const buttonVariants = cva(
  [
    'inline-flex items-center justify-center',
    'select-none appearance-none outline-none',
    'whitespace-nowrap border transition-colors',
    'rounded',
    'focus-visible:ring',
  ],
  {
    variants: {
      size: { xs: 'h-6 px-2 text-sm', sm: 'h-7 px-3', md: 'h-8 px-4', lg: 'h-9 px-5', xl: 'h-10 px-6 text-lg' },
      variant: {
        solid: 'text-fg-emphasized border-transparent',
        outline: 'bg-bg-default border-current',
        light: 'border-transparent',
        subtle: 'border-transparent bg-bg-default',
        link: 'border-transparent underline underline-offset-2',
      },
      color: {
        primary: 'focus-visible:ring-bg-primary-pressed/70',
        neutral: 'focus-visible:ring-bg-neutral-pressed/70',
        success: 'focus-visible:ring-bg-success-pressed/70',
        warning: 'focus-visible:ring-bg-warning-pressed/70',
        danger: 'focus-visible:ring-bg-danger-pressed/70',
      },
      disabled: {
        true: 'cursor-not-allowed opacity-50',
        false: '',
      },
      active: {
        true: '',
        false: '',
      },
    },
    compoundVariants: [
      {
        variant: 'solid',
        color: 'primary',
        active: false,
        class: 'bg-bg-primary-emphasis',
      },
      {
        variant: 'solid',
        color: 'primary',
        active: true,
        class: 'bg-bg-primary-emphasis-pressed',
      },
      {
        variant: 'solid',
        color: 'primary',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-primary-emphasis-hovered active:bg-bg-primary-emphasis-pressed',
      },
      {
        variant: 'solid',
        color: 'neutral',
        active: false,
        class: 'bg-bg-neutral-emphasis',
      },
      {
        variant: 'solid',
        color: 'neutral',
        active: true,
        class: 'bg-bg-neutral-emphasis-pressed',
      },
      {
        variant: 'solid',
        color: 'neutral',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-neutral-emphasis-hovered active:bg-bg-neutral-emphasis-pressed',
      },
      {
        variant: 'solid',
        color: 'success',
        active: false,
        class: 'bg-bg-success-emphasis',
      },
      {
        variant: 'solid',
        color: 'success',
        active: true,
        class: 'bg-bg-success-emphasis-pressed',
      },
      {
        variant: 'solid',
        color: 'success',
        active: false,
        disabled: false,
        class: 'hover:bg-bg-success-emphasis-hovered active:bg-bg-success-emphasis-pressed',
      },
      {
        variant: 'solid',
        color: 'warning',
        active: false,
        class: 'bg-bg-warning-emphasis',
      },
      {
        variant: 'solid',
        color: 'warning',
        active: true,
        class: 'bg-bg-warning-emphasis-pressed',
      },
      {
        variant: 'solid',
        color: 'warning',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-warning-emphasis-hovered active:bg-bg-warning-emphasis-pressed',
      },
      {
        variant: 'solid',
        color: 'danger',
        active: false,
        class: 'bg-bg-danger-emphasis',
      },
      {
        variant: 'solid',
        color: 'danger',
        active: true,
        class: 'bg-bg-danger-emphasis-pressed',
      },
      {
        variant: 'solid',
        color: 'danger',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-danger-emphasis-hovered active:bg-bg-danger-emphasis-pressed',
      },
      {
        variant: 'outline',
        color: 'primary',
        class: 'text-fg-primary',
      },
      {
        variant: 'outline',
        color: 'primary',
        active: true,
        class: 'bg-bg-primary-hovered',
      },
      {
        variant: 'outline',
        color: 'primary',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-primary active:bg-bg-primary-hovered',
      },
      {
        variant: 'outline',
        color: 'success',
        class: 'text-fg-success',
      },
      {
        variant: 'outline',
        color: 'success',
        active: true,
        class: 'bg-bg-success-hovered',
      },
      {
        variant: 'outline',
        color: 'success',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-success active:bg-bg-success-hovered',
      },
      {
        variant: 'outline',
        color: 'warning',
        class: 'text-fg-warning',
      },
      {
        variant: 'outline',
        color: 'warning',
        active: true,
        class: 'bg-bg-warning-hovered',
      },
      {
        variant: 'outline',
        color: 'warning',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-warning active:bg-bg-warning-hovered',
      },
      {
        variant: 'outline',
        color: 'danger',
        class: 'text-fg-danger',
      },
      {
        variant: 'outline',
        color: 'danger',
        active: true,
        class: 'bg-bg-danger-hovered',
      },
      {
        variant: 'outline',
        color: 'danger',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-danger active:bg-bg-danger-hovered',
      },
      {
        variant: 'outline',
        color: 'neutral',
        class: 'text-fg-neutral',
      },
      {
        variant: 'outline',
        color: 'neutral',
        active: true,
        class: 'bg-bg-neutral-hovered',
      },
      {
        variant: 'light',
        color: 'primary',
        active: false,
        class: 'text-fg-primary bg-bg-primary',
      },
      {
        variant: 'light',
        color: 'primary',
        active: true,
        class: 'text-fg-primary bg-bg-primary-pressed',
      },
      {
        variant: 'light',
        color: 'primary',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-primary-hovered active:bg-bg-primary-pressed',
      },
      {
        variant: 'light',
        color: 'success',
        active: false,
        class: 'text-fg-success bg-bg-success',
      },
      {
        variant: 'light',
        color: 'success',
        active: true,
        class: 'text-fg-success bg-bg-success-pressed',
      },
      {
        variant: 'light',
        color: 'success',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-success-hovered active:bg-bg-success-pressed',
      },
      {
        variant: 'light',
        color: 'warning',
        active: false,
        class: 'text-fg-warning bg-bg-warning',
      },
      {
        variant: 'light',
        color: 'warning',
        active: true,
        class: 'text-fg-warning bg-bg-warning-pressed',
      },
      {
        variant: 'light',
        color: 'warning',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-warning-hovered active:bg-bg-warning-pressed',
      },
      {
        variant: 'light',
        color: 'danger',
        active: false,
        class: 'text-fg-danger bg-bg-danger',
      },
      {
        variant: 'light',
        color: 'danger',
        active: true,
        class: 'text-fg-danger bg-bg-danger-pressed',
      },
      {
        variant: 'light',
        color: 'danger',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-danger-hovered active:bg-bg-danger-pressed',
      },
      {
        variant: 'light',
        color: 'neutral',
        active: false,
        class: 'text-fg-neutral bg-bg-neutral',
      },
      {
        variant: 'light',
        color: 'neutral',
        active: true,
        class: 'text-fg-neutral bg-bg-neutral-pressed',
      },
      {
        variant: 'light',
        color: 'neutral',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-neutral-hovered active:bg-bg-neutral-pressed',
      },
      {
        variant: 'subtle',
        color: 'primary',
        class: 'text-fg-primary',
      },
      {
        variant: 'subtle',
        color: 'primary',
        active: true,
        class: 'bg-bg-primary-hovered',
      },
      {
        variant: 'subtle',
        color: 'primary',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-primary active:bg-bg-primary-hovered',
      },
      {
        variant: 'subtle',
        color: 'success',
        class: 'text-fg-success',
      },
      {
        variant: 'subtle',
        color: 'success',
        active: true,
        class: 'bg-bg-success-hovered',
      },
      {
        variant: 'subtle',
        color: 'success',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-success active:bg-bg-success-hovered',
      },
      {
        variant: 'subtle',
        color: 'warning',
        class: 'text-fg-warning',
      },
      {
        variant: 'subtle',
        color: 'warning',
        active: true,
        class: 'bg-bg-warning-hovered',
      },
      {
        variant: 'subtle',
        color: 'warning',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-warning active:bg-bg-warning-hovered',
      },
      {
        variant: 'subtle',
        color: 'danger',
        class: 'text-fg-danger',
      },
      {
        variant: 'subtle',
        color: 'danger',
        active: true,
        class: 'bg-bg-danger-hovered',
      },
      {
        variant: 'subtle',
        color: 'danger',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-danger active:bg-bg-danger-hovered',
      },
      {
        variant: 'subtle',
        color: 'neutral',
        class: 'text-fg-neutral',
      },
      {
        variant: 'subtle',
        color: 'neutral',
        active: true,
        class: 'bg-bg-neutral-hovered',
      },
      {
        variant: 'subtle',
        color: 'neutral',
        disabled: false,
        active: false,
        class: 'hover:bg-bg-neutral active:bg-bg-neutral-hovered',
      },
      {
        variant: 'link',
        color: 'primary',
        active: false,
        class: 'text-fg-primary',
      },
      {
        variant: 'link',
        color: 'primary',
        active: true,
        class: 'text-fg-primary-pressed',
      },
      {
        variant: 'link',
        color: 'primary',
        disabled: false,
        active: false,
        class: 'hover:text-fg-primary-hovered active:text-fg-primary-pressed',
      },
      {
        variant: 'link',
        color: 'success',
        active: false,
        class: 'text-fg-success',
      },
      {
        variant: 'link',
        color: 'success',
        active: true,
        class: 'text-fg-success-pressed',
      },
      {
        variant: 'link',
        color: 'success',
        disabled: false,
        active: false,
        class: 'hover:text-fg-success-hovered active:text-fg-success-pressed',
      },
      {
        variant: 'link',
        color: 'warning',
        active: false,
        class: 'text-fg-warning',
      },
      {
        variant: 'link',
        color: 'warning',
        active: true,
        class: 'text-fg-warning-pressed',
      },
      {
        variant: 'link',
        color: 'warning',
        disabled: false,
        active: false,
        class: 'hover:text-fg-warning-hovered active:text-fg-warning-pressed',
      },
      {
        variant: 'link',
        color: 'danger',
        active: false,
        class: 'text-fg-danger',
      },
      {
        variant: 'link',
        color: 'danger',
        active: true,
        class: 'text-fg-danger-pressed',
      },
      {
        variant: 'link',
        color: 'danger',
        disabled: false,
        active: false,
        class: 'hover:text-fg-danger-hovered active:text-fg-danger-pressed',
      },
      {
        variant: 'link',
        color: 'neutral',
        active: false,
        class: 'text-fg-neutral',
      },
      {
        variant: 'link',
        color: 'neutral',
        active: true,
        class: 'text-fg-neutral-pressed',
      },
      {
        variant: 'link',
        color: 'neutral',
        disabled: false,
        active: false,
        class: 'hover:text-fg-neutral-hovered active:text-fg-neutral-pressed',
      },
    ],
  }
);

export type ButtonVariants = VariantProps<typeof buttonVariants>;
